### PR TITLE
remove unneeded `Local Development Notes` command from README (for #20)

### PR DESCRIPTION
**Pull request by cvan**
will flesh out notes later /cc @caseyyee

### CODE REVIEW

**Comment by caseyyee** [comment]
Thought this was useful even if it was a bit rough.    I would keep until we have suitable replacement IMO.  Up to you.

**Comment by cvan** [comment]
I should remove the soft links though (Unity doesn't like them). I just use `sync.sh` right now - what do you use?

**Comment by caseyyee** [comment]
Gotcha.  yeah, never tried with the soft links.    I also just use sync.

**Comment by cvan** [comment]
updated, @caseyyee

**Pull request merged**
