### PR TITLE
Issue 19: WebVR camera position overwrites unity entity 

### PR DESCRIPTION
**Pull request by pweingar**
Updated WebVR camera code to update the position of the Unity entity relative to the parent and additive to the original local position.

### CODE REVIEW

**Comment by caseyyee** [comment]
Thanks!   Will give this a try.   Can we flatten the commits?

**Comment by pweingar** [comment]
Oh yes... should just be formatting changes. The way I updated the code in git ended up changing a bunch of your formatting, which I didn't realize until I committed.

**Comment by gtk2k** [comment]
I'm sorry for delay.
@pweingar Thanks PR !
@caseyyee @cvan May I merge OK?

**Comment by caseyyee** [comment]
Yes, this works well for me 👍 

Thanks for the patch @pweingar !

**Pull request merged**
